spring.application.name=eureka-server
server.port=8761

# Serveur autonome : ne s'enregistre pas comme client aupres de lui-meme
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


spring.security.user.name=${EUREKA_USER:eureka}
spring.security.user.password=${EUREKA_PASSWORD:eurekapass}
